export const ITEM__CREATE = 'ITEM__CREATE'
export const FLASH_MESSAGE__CREATE = 'FLASH_MESSAGE__CREATE'
export const FLASH_MESSAGE__DELETE = 'FLASH_MESSAGE__DELETE'
export const ADMIN_LOGIN = 'ADMIN_LOGIN'
